#!/bin/bash

#This script is called on startup

export PATH="$PATH:$HOME/.local/bin"

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_CACHE_HOME/zsh/history"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export VSCODE_PORTABLE="$XDG_DATA_HOME"/vscode
export VSCODIUM_PORTABLE="$XDG_DATA_HOME"/vscode

# export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export KDEHOME="$XDG_CONFIG_HOME"/kde
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
#export XAUTHORITY="$XDG_DATA_HOME"/xorg/Xauthority
export WAKATIME_HOME="$XDG_CONFIG_HOME/wakatime"
export GNUPGHOME="$XDG_DATA_HOME"/gnupg

# NVIDIA stuff
export __GL_THREADED_OPTIMIZATION=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME"/shaders
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia

# DevKitPro
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPPC=/opt/devkitpro/devkitPPC

# Raspberry Pi Pico SDK
export PICO_SDK_PATH=$(whereis pico-sdk | cut -d ' ' -f2)
export PICO_EXTRAS_PATH=$HOME/.local/lib/pico-extras

export PATH="$PATH:$DEVKITPRO/tools/bin"

# Debug symbols
# source /etc/profile.d/debuginfod.sh
